;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cargo.Coffee",DevComment="")
+GameplayTagList=(Tag="Cargo.Seeds",DevComment="")
+GameplayTagList=(Tag="Cargo.Whiskey",DevComment="")
+GameplayTagList=(Tag="Choice.GiveSeedsToStarving",DevComment="")
+GameplayTagList=(Tag="Dialogue.Banana1",DevComment="")
+GameplayTagList=(Tag="Dialogue.Banana2",DevComment="")
+GameplayTagList=(Tag="Dialogue.BananaDeliveryEnd",DevComment="")
+GameplayTagList=(Tag="Dialogue.BananaDeliveryEndAlt",DevComment="")
+GameplayTagList=(Tag="Dialogue.BananaFinish",DevComment="")
+GameplayTagList=(Tag="Dialogue.StarvingIsland",DevComment="")
+GameplayTagList=(Tag="Dialogue.Test",DevComment="")
+GameplayTagList=(Tag="Location.FirstIsland",DevComment="")
+GameplayTagList=(Tag="Location.NorringtonIsland",DevComment="")
+GameplayTagList=(Tag="Location.StarvingIsland",DevComment="")
+GameplayTagList=(Tag="Quest.Banana",DevComment="")
+GameplayTagList=(Tag="Quest.SeedsToNorrington",DevComment="")

