;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Quest.GoToMinerIsland",NewTagName="Quest.GoToMiningIsland")
+GameplayTagList=(Tag="Cargo.Coffee",DevComment="")
+GameplayTagList=(Tag="Cargo.Iron",DevComment="")
+GameplayTagList=(Tag="Cargo.RoastMachine",DevComment="")
+GameplayTagList=(Tag="Cargo.Seeds",DevComment="")
+GameplayTagList=(Tag="Cargo.Whiskey",DevComment="")
+GameplayTagList=(Tag="Choice.GiveSeedsToStarving",DevComment="")
+GameplayTagList=(Tag="Choice.HelpWreckedShip",DevComment="")
+GameplayTagList=(Tag="Dialogue.Banana1",DevComment="")
+GameplayTagList=(Tag="Dialogue.Banana2",DevComment="")
+GameplayTagList=(Tag="Dialogue.BananaDeliveryEnd",DevComment="")
+GameplayTagList=(Tag="Dialogue.BananaDeliveryEndAlt",DevComment="")
+GameplayTagList=(Tag="Dialogue.BananaFinish",DevComment="")
+GameplayTagList=(Tag="Dialogue.CoffeeToMining.DeliveryEnd",DevComment="")
+GameplayTagList=(Tag="Dialogue.CoffeeToMining.DeliveryStart",DevComment="")
+GameplayTagList=(Tag="Dialogue.CoffeeToMining.Progress",DevComment="")
+GameplayTagList=(Tag="Dialogue.CoffeeToMining.Start",DevComment="")
+GameplayTagList=(Tag="Dialogue.GoToMining.End",DevComment="")
+GameplayTagList=(Tag="Dialogue.GoToMining.Progress",DevComment="")
+GameplayTagList=(Tag="Dialogue.GoToMining.Start",DevComment="")
+GameplayTagList=(Tag="Dialogue.GoToTecno.End",DevComment="")
+GameplayTagList=(Tag="Dialogue.GoToTecno.Progress",DevComment="")
+GameplayTagList=(Tag="Dialogue.GoToTecno.Start",DevComment="")
+GameplayTagList=(Tag="Dialogue.InitialQuest.InProgress",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToTecno.DeliveryEnd",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToTecno.DeliveryStart",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToTecno.Progress",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToTecno.Start",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToWreckedShip.AcceptQuest",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToWreckedShip.DeclineQuest",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToWreckedShip.DeliveryEnd",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToWreckedShip.DeliveryStart",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToWreckedShip.InitialDialogue",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToWreckedShip.Progress",DevComment="")
+GameplayTagList=(Tag="Dialogue.IronToWreckedShip.Start",DevComment="")
+GameplayTagList=(Tag="Dialogue.RoasterToNorrington.DeliveryEnd",DevComment="")
+GameplayTagList=(Tag="Dialogue.RoasterToNorrington.DeliveryStart",DevComment="")
+GameplayTagList=(Tag="Dialogue.RoasterToNorrington.Progress",DevComment="")
+GameplayTagList=(Tag="Dialogue.RoasterToNorrington.Start",DevComment="")
+GameplayTagList=(Tag="Dialogue.StarvingIsland",DevComment="")
+GameplayTagList=(Tag="Dialogue.Test",DevComment="")
+GameplayTagList=(Tag="Location.FirstIsland",DevComment="")
+GameplayTagList=(Tag="Location.Miners",DevComment="")
+GameplayTagList=(Tag="Location.NorringtonIsland",DevComment="")
+GameplayTagList=(Tag="Location.StarvingIsland",DevComment="")
+GameplayTagList=(Tag="Location.TecnologyIsland",DevComment="")
+GameplayTagList=(Tag="Location.WreckedShip",DevComment="")
+GameplayTagList=(Tag="Quest.CoffeeToMining",DevComment="")
+GameplayTagList=(Tag="Quest.GoToMiningIsland",DevComment="")
+GameplayTagList=(Tag="Quest.GoToTecnoIsland",DevComment="")
+GameplayTagList=(Tag="Quest.IronToTecno",DevComment="")
+GameplayTagList=(Tag="Quest.IronToWreckedShip",DevComment="")
+GameplayTagList=(Tag="Quest.RoasterToNorrington",DevComment="")
+GameplayTagList=(Tag="Quest.SeedsToNorrington",DevComment="")

